#!/bin/zsh

# Startup
startup.sh &

# Variables
layoutGenerator=rivertile
mod="Mod4"

# Aestethics
riverctl background-color "0x4C566A"
riverctl border-color-focused "0x81A1C1"
riverctl border-color-unfocused "0x00000000"
riverctl border-width 2

# Misc
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-output-change
riverctl xcursor-theme capitaine-cursors

# Input
riverctl input 9610:30:Pine64_Pinebook_Pro_Touchpad middle-emulation enabled
riverctl input 9610:30:Pine64_Pinebook_Pro_Touchpad natural-scroll enabled
riverctl input 9610:30:Pine64_Pinebook_Pro_Touchpad tap enabled
riverctl input 9610:30:Pine64_Pinebook_Pro_Touchpad disable-while-typing enabled
riverctl set-repeat 60 300

# Programs
riverctl map normal $mod F1 spawn "helpmenu"
riverctl map normal $mod Return spawn "foot"
riverctl map normal $mod D spawn "j4-dmenu-desktop --dmenu=launcher --no-generic --term=foot"
riverctl map normal $mod+Shift D spawn "launcher-run"
riverctl map normal $mod V spawn "otp.sh"
riverctl map normal $mod+Shift N spawn "yambar"
riverctl map normal Mod4 P spawn "autorandr.sh && killall yambar && yambar"
riverctl map normal Mod4+Shift P spawn "monitormenu.sh"

riverctl map normal None Super_L spawn "yambarnotify.sh"
riverctl map -release normal Mod4 Super_L spawn "yambarnotify-close.sh"

# Window navigation
riverctl map normal $mod+Shift Q close
riverctl map normal $mod+Shift Q spawn "focuslariza quit"

riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

riverctl map normal $mod+Shift Return zoom

riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

riverctl map normal $mod H send-layout-cmd $layoutGenerator "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd $layoutGenerator "main-ratio +0.05"

riverctl map normal $mod+Shift H send-layout-cmd $layoutGenerator "main-count -1"
riverctl map normal $mod+Shift L send-layout-cmd $layoutGenerator "main-count -1"

riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# Tag management
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod $i spawn "focuslariza focus $tags"

    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Shift $i spawn "focuslariza move $tags"

    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

riverctl map normal $mod+Shift Space toggle-float
riverctl map normal $mod F toggle-fullscreen

# Passtrough
riverctl declare-mode passthrough
riverctl map normal None F11 enter-mode passthrough
riverctl map passthrough None F11 enter-mode normal

for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn "set-volume.sh +10%"
    riverctl map $mode None XF86AudioLowerVolume  spawn "set-volume.sh -10%"
    riverctl map $mode Shift XF86AudioRaiseVolume  spawn "set-volume.sh +1%"
    riverctl map $mode Shift XF86AudioLowerVolume  spawn "set-volume.sh -1%"
    riverctl map $mode None XF86AudioMute         spawn "set-audio-output.sh"

    riverctl map $mode Shift XF86MonBrightnessUp   spawn "exposure.sh \*"
    riverctl map $mode Shift XF86MonBrightnessDown spawn "exposure.sh /"

    riverctl map $mode None XF86Poweroff spawn "menupower-river.sh"

    riverctl map $mode None Print spawn "screenshot output"
    riverctl map $mode Shift Print spawn "screenshot area"
done

# Floating rules
riverctl float-filter-add app-id "float"
riverctl float-filter-add app-id "popup"

riverctl float-filter-add app-id "file-roller"
riverctl float-filter-add title "File Operation Progress"

riverctl float-filter-add app-id "yad"

riverctl float-filter-add title "BlocKit"
riverctl float-filter-add title "lariza - Download Manager"

riverctl float-filter-add title "Firefox — Sharing Indicator"

riverctl float-filter-add title "Change Foreground Color"
riverctl float-filter-add title "Quit GIMP"
riverctl float-filter-add title "New Layer"
riverctl float-filter-add title "Layer Attributes"

riverctl float-filter-add title "swayimg: /tmp/tuir"

riverctl float-filter-add app-id "udiskie"

riverctl float-filter-add app-id "launcher"
riverctl csd-filter-add app-id "launcher"

# Layout generator
riverctl default-layout $layoutGenerator
exec $layoutGenerator -outer-padding 0 -view-padding 5 
